server {

    # NGINX listens on port 80 inside its container
    listen 80;

    location / {

        # Send traffic to the Next.js service
        # Docker DNS resolves "pos-app"
        proxy_pass http://pos-app:3000;

        # Forward useful client information
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}